#
###################################
# Site wide configuration
####################################
#
title: Rafael N. Magalhães
email: rnunesmagalhaes@gmail.com
description: 
url: http://rmagalhaes.com


#
###################################
# Jekyll configuration
####################################
#
timezone:          
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Rafael N. Magalhães
  avatar: 
  job: Political Science & Stats
  bio: 
  email: rnunesmagalhaes@gmail.com
  disqus-shortname:
  twitter: rnunesmagalhaes
  facebook: #username
  google:
    plus: #username
    analytics: 84872368
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rnunesmagalhaes
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
